### ISSUE TITLE
When winning and choosing to generate a new game, then leaving the game before completing the game, the shipment platform will be unrepaired

### ISSUE THREAD

**Issue by ThomasMartinOctoPi** [OctoPi-Team/OctoPi#183]
probably should move the flag on completemnet not on the button"return to overworld" in the winning screen, but idk 

https://github.com/OctoPi-Team/OctoPi/assets/129731653/546bce73-b05b-4410-9f09-8bd20d9d7ade

**Comment by JasminTsch** [comment]
When winning and then leaving the game with the "<-" button, the shipment platform will be unrepaired

**Comment by JasminTsch** [comment]
fixed with branch bugfix #138
