### ISSUE TITLE
Old collision box doesnt get deleted if an object is moved

### ISSUE THREAD

**Issue by schmitt-steven** [OctoPi-Team/OctoPi#212]
**Describe the bug**
Old collision box doesnt get deleted if an object is moved, meaning there are two collision boxed for 1 object that was moved

**To Reproduce**

1. Repair shipment platform
2. Walk to the spot where the 'Ameisenwagen' was placed originally

**Desktop (please complete the following information):**

- OS: Linux
- Browser: chrome

**Comment by ThomasMartinOctoPi** [comment]
fixed with pr #218

**Comment by ThomasMartinOctoPi** [comment]
maybe not....
