### ISSUE TITLE
Player doesn't move after clicking the start button

### ISSUE THREAD

**Issue by schmitt-steven** [OctoPi-Team/OctoPi#32]
**Describe the bug**
Player doesn't move after clicking the start button, a left mouse click is needed otherwise the arrow keys have no use.

**To Reproduce**

1. Wait until the game is loaded
2. Click on 'start'
3. Now the player character is stuck, a left click is needed to enable movement

**Expected behavior**
After clicking the start button, the character should move by pressing the arrow keys.

**Screenshots**
Not applicable for this issue

**Desktop (please complete the following information):**
Chrome, latest release

**Comment by timowenz** [comment]
And of course i couldnt fix it LOL
