### ISSUE TITLE
Long Loading Time

### ISSUE THREAD

**Issue by pIlIp-d** [OctoPi-Team/OctoPi#41]
**Describe the bug**
When Loading the page the startscreen loads for around 15 seconds each time

**To Reproduce**

(0. Start Server)
2. Open URL to website
3. wait too long

**Expected behavior**
Opening the page having the scene load at least in under 5 seconds if not immediately.

- OS: Linux
- Browser Chromium
- Version 113.0.5672.126

**Comment by timowenz** [comment]
Should be fixed with compressed images or?

**Comment by pIlIp-d** [comment]
Fixed with .obj to .glb conversion in combination with .glb compression via draco.
