### ISSUE TITLE
Back Button Keeps Player Moving

### ISSUE THREAD

**Issue by pIlIp-d** [OctoPi-Team/OctoPi#45]
**Describe the bug**
When I'm inside the shipment minigame and want to go back to the overworld the player movement is locked in. (In Addition to that the player doesnt spawn at the minigame Position.)

**To Reproduce**

1. Go into the minigame (using only the keyboard controls)
2. Click on 'Spiel verlassen'
3. Observe

**Expected behavior**
Spawn at the Entry of the Minigame on the corresponding platform, without moving at all.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Chromium
- Version 113.0.5672.126

**Additional Context**
When Using the Joystick the problem doesnt occur.

**Comment by timowenz** [comment]
Should be fixed
