### ISSUE TITLE
Lag on Ipad

### ISSUE THREAD

**Issue by pIlIp-d** [OctoPi-Team/OctoPi#55]
**Describe the bug**
The Game is unplayable on some IPads. Game loads very long and lags a lot.

**To Reproduce**

1. Go to live version of main branch deployment (DEMO link in README.md)
2. wait until its loaded
3. Click on 'Start'
4. Move around

**Expected behavior**
Smooth moving around, no lags.

**Tablet (please complete the following information):**

- Device: IPad Pro 2017
- OS: IPad-OS 16.5
- Browser safari

**Comment by schmitt-steven** [comment]
Same on Iphone 11 with Safari, the game just breaks
![image](https://github.com/OctoPi-Team/OctoPi/assets/82405062/177cba1f-cf9b-47c1-8596-674354872b3f)
