### ISSUE TITLE
Screensaver zooms camera extremely far out

### ISSUE THREAD

**Issue by ThomasMartinOctoPi** [OctoPi-Team/OctoPi#79]
When the screensaver triggers and the user presses "start" the camera will be zoomed out very far out
**To Reproduce**

1. Wait for screensaver to trigger
2. Click on 'Start'
3. See error

**Expected behavior**
Player position should be reset to origin position and camera should obviously not zoom out
**Screenshots**

![image](https://github.com/OctoPi-Team/OctoPi/assets/129731653/dbe32c74-29e6-48cb-89cc-4d27e41ba6da)

**_ADDITIONALLY_**
When viewing the zoomed Overwold and pressing any button, beginning animation will play, why??

**Comment by schmitt-steven** [comment]
Fixed with camera zoom
