### ISSUE TITLE
ShipmentGame: THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by pIlIp-d** [OctoPi-Team/OctoPi#80]
**Describe the bug**
The Error THREE.WebGLRenderer: Context Lost. occurs every time when entering the shipment game. On Chrome the browser fixes itself, but on IOS and iPadOS it crashes the application completely.

**To Reproduce**
1. Go to the Shipment Minigame
2. Watch the console or see the game crash.

**Expected behavior**
Not crash and have a stable transition between scenes.

**Desktop (please complete the following information):**

- OS: ubuntu 22.04
- Browser chromium

**Tablet (please complete the following information):**

- Device: iPad Pro 2017
- OS: 16.5
- Browser safari

**Additional context**
Error was already in the code since at least morning 08.06.2023

**Comment by timowenz** [comment]
Tested it with my iPad and there was no crash or bug with Safari or iOS. We should observe the problem.

[Also I found this comment](https://github.com/pmndrs/react-three-fiber/discussions/1151)
