### ISSUE TITLE
Wrong combination of tubes can win the mini game

### ISSUE THREAD

**Issue by schmitt-steven** [OctoPi-Team/OctoPi#98]
**Describe the bug**
Even with a wrong combination of tubes the game can be won and the morphing together 

**To Reproduce**

1. Go to shipment mini game
2. Get a correct tube formation except one wrong tile. The tile must be a straight inverted tile
3. Game is then  won even though the combination is wrong

**Comment by ThomasMartinOctoPi** [comment]
Should be fixed (open pull request #99 )
